### ISSUE TITLE
Safe prime generation is disabled

### ISSUE THREAD

**Issue by nkatual123** [mhe/irmatool#2]
Hi,
    Getting safe prime generation issue while execute below script in irmatool . I need to create custom scheme manager for IRMA application. 

    
C:\go-ws\src\github.com\mhe\irmatool> irmatool genkeypair -a 6 -l 2048 -c 0 -p ipk.xml -k isk.xml
**panic: Safe prime generation is disabled**

goroutine 1 [running]:
github.com/credentials/safeprime.Generate(...)
        C:/go-ws/src/github.com/credentials/safeprime/safeprime_stub.go:10
github.com/mhe/gabi.GenerateKeyPair(0xc0000a0070, 0x6, 0x0, 0x31756d00, 0xed6041469, 0xc9e740, 0x31756d00, 0xed6041469, 0xc9e740, 0x8010102)
        C:/go-ws/src/github.com/mhe/gabi/keys.go:346 +0x48
github.com/mhe/irmatool/cmd.glob..func1(0xc96160, 0xc000047b80, 0x0, 0xa, 0x0, 0x0)
        C:/go-ws/src/github.com/mhe/irmatool/cmd/genkeypair.go:116 +0x405
github.com/spf13/cobra.(*Command).execute(0xc96160, 0xc000047a40, 0xa, 0xa, 0xc96160, 0xc000047a40)
        C:/go-ws/src/github.com/spf13/cobra/command.go:762 +0x46c
github.com/spf13/cobra.(*Command).ExecuteC(0xc963c0, 0x8ee849, 0x17, 0x1)
        C:/go-ws/src/github.com/spf13/cobra/command.go:852 +0x2c7
github.com/spf13/cobra.(*Command).Execute(...)
        C:/go-ws/src/github.com/spf13/cobra/command.go:800
github.com/mhe/irmatool/cmd.Execute()
        C:/go-ws/src/github.com/mhe/irmatool/cmd/root.go:47 +0x39
main.main()
        C:/go-ws/src/github.com/mhe/irmatool/main.go:26 +0x27

Can anyone help

**Comment by mhe** [comment]
This irmatool is only lightly mainted. I would advice you to checkout https://github.com/privacybydesign/irmago. It includes commands to generate keys. See also https://irma.app/docs/ for documentation.
